# Generated by Django 2.2 on 2020-07-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images_plants/%Y/%m/%d/')),
                ('prediction', models.CharField(max_length=50)),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
