# Generated by Django 2.2 on 2020-07-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='accuracy',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
