# Generated by Django 2.2 on 2020-07-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0002_auto_20200708_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='classification',
            name='prediction',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
